name: Check ALM Client Installation

on: [push, pull_request]

jobs:
  check-alm-client:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up ALM Client
      run: |
        # Replace with the correct installation command for ALM client
        # Example: Download and install ALM client
        Invoke-WebRequest -Uri 'http://example.com/alm-client-installer.exe' -OutFile 'alm-client-installer.exe'
        Start-Process 'alm-client-installer.exe' -ArgumentList '/silent' -Wait
      shell: pwsh

    - name: Register COM Library
      run: |
        # Register the required COM library
        regsvr32 "C:\\Path\\To\\Mercury.TD.Client.Ota.QC9.dll"
      shell: cmd

    - name: Verify ALM Client Installation
      run: |
        # Run a script to verify that the ALM client works correctly
        .\path\to\your\verification\script.ps1
      shell: pwsh
