name: Run PowerShell Script

on: [push, pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Set HELPER_SCRIPTS Environment Variable
      run: echo "HELPER_SCRIPTS=$GITHUB_WORKSPACE/images/ubuntu/scripts/build" >> $GITHUB_ENV

    - name: Run Install-PowerShellAzModules.ps1
      run: pwsh ./images/ubuntu/scripts/build/Install-PowerShellAzModules.ps1
      shell: pwsh
