name: Run Install-PowerShellAzModules Script

on: [push, pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Install-PowerShellAzModules.ps1
      run: pwsh ./images/ubuntu/scripts/build/Install-PowerShellAzModules.ps1
      shell: pwsh
