name: List Available Az Modules

on: [push, pull_request]

jobs:
  list-az-modules:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: List Az Modules
      run: |
        pwsh -command "Get-Module -Name Az.* -ListAvailable"
