name: Check Az Modules

on: [push, pull_request]

jobs:
  check-az-modules:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install Az Modules
      run: Install-Module -Name Az -AllowClobber -Force -Scope CurrentUser
      shell: pwsh
    
    - name: List Az Modules
      run: Get-Module -Name Az.* -ListAvailable
      shell: pwsh
