name: Check .NET SDK Version

on: 
  push:
    branches:
      - dotnet
  pull_request:
    branches:
      - dotnet

jobs:
  check-dotnet-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, ubuntu-24.04]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install .NET SDK 9.0.100
      run: |
        wget https://dotnetcli.azureedge.net/dotnet/Sdk/9.0.100/dotnet-sdk-9.0.100-linux-x64.tar.gz
        mkdir -p $HOME/dotnet
        tar zxf dotnet-sdk-9.0.100-linux-x64.tar.gz -C $HOME/dotnet
        export DOTNET_ROOT=$HOME/dotnet
        export PATH=$PATH:$HOME/dotnet

    - name: Check .NET SDK Version
      run: |
        dotnet --version
