name: Install Microsoft Edge

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-edge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        echo "HELPER_SCRIPTS=$(pwd)/images/ubuntu/scripts/helpers" >> $GITHUB_ENV
        source $HELPER_SCRIPTS/etc-environment.sh

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y wget gnupg curl unzip

    - name: Run install-microsoft-edge.sh script
      run: sudo bash images/ubuntu/scripts/build/install-microsoft-edge.sh
