name: Install .NET SDK 9 and Verify Installation

on:
  push:
    branches:
      - dotnet
  pull_request:
    branches:
      - dotnet

jobs:
  check-dotnet-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, ubuntu-24.04]
        
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install curl and tar
      run: sudo apt-get update && sudo apt-get install -y curl tar

    - name: Set version number
      run: echo "VERSION=9.0.100" >> $GITHUB_ENV  # Set the version of the .NET SDK to install

    - name: Download .NET SDK
      run: |
        url="https://dotnetcli.blob.core.windows.net/dotnet/Sdk/${{ env.VERSION }}/dotnet-sdk-${{ env.VERSION }}-linux-x64.tar.gz"
        echo "Downloading .NET SDK version ${{ env.VERSION }} from $url"
        curl -sSL $url -o dotnet-sdk.tar.gz

    - name: Extract .NET SDK
      run: |
        mkdir -p $HOME/dotnet
        tar -xzf dotnet-sdk.tar.gz -C $HOME/dotnet

    - name: Add .NET to PATH
      run: |
        echo "$HOME/dotnet" >> $GITHUB_PATH  # Adds the .NET SDK location to the PATH

    - name: Verify .NET SDK installation
      run: dotnet --version  # Verify the installed version
