name: Check pip Version

on: [push, pull_request]

jobs:
  check-pip-version:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Check pip version
        run: pip -V
