name: Install Specific Pip and Dropbox Version

on: [push]

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check current pip version
      run: python -m pip --version

    - name: Install specific pip version (less than 24.1)
      run: |
        python -m pip install --upgrade "pip 22"
        python -m pip --version

    - name: Install dropbox package
      run: |
        python -m pip install dropbox==11.36.2  # Use a compatible version
        python -m pip list | grep dropbox
