name: Python Setup Test

on: [push]

jobs:
  setup-python:
    runs-on: windows-2022

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Change this version as needed

      - name: Verify Python installation
        run: |
          python --version
