name: Python Setup Test

on: [push]

jobs:
  setup-python:
    runs-on: windows-2022

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python versions
        run: |
          python_versions=("3.7.x" "3.8.x" "3.9.x" "3.10.x" "3.11.x" "3.12.x")
          for version in "${python_versions[@]}"; do
            echo "Setting up Python $version"
            echo "::set-output name=python-version::$version"
            echo "::group::Setting up Python $version"
            echo "Setting up Python $version"
            echo "::endgroup::"
            python --version
          done
          echo "Installed Python versions:"
          for version in "${python_versions[@]}"; do
            if python -c "import sys; sys.exit(0 if sys.version.startswith('$version') else 1)"; then
              echo "$version is installed"
            else
              echo "$version is not installed"
            fi
          done
        shell: bash

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7.x'

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.x'

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.x'

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.x'

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.x'
