name: Python Setup Test

on: [push]

jobs:
  setup-python:
    runs-on: windows-2022

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python versions
        run: |
          python_versions=("3.7.x" "3.8.x" "3.9.x" "3.10.x" "3.11.x" "3.12.x")
          for version in "${python_versions[@]}"; do
            echo "Setting up Python $version"
            actions/setup-python@v4 --python-version $version
            python --version
          done
          echo "Installed Python versions:"
          for version in "${python_versions[@]}"; do
            if python -c "import sys; sys.exit(0 if sys.version.startswith('$version') else 1)"; then
              echo "$version is installed"
            else
              echo "$version is not installed"
            fi
          done
        shell: bash
