name: Install Specific Sudo Version

on: push

jobs:
  install-sudo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download specific sudo version
      run: wget https://www.sudo.ws/sudo/dist/sudo-1.9.9.tar.gz

    - name: Extract downloaded tarball
      run: tar -xvf sudo-1.9.9.tar.gz

    - name: Change directory to extracted folder
      run: cd sudo-1.9.9

    - name: Compile sudo
      run: make

    - name: Install sudo
      run: sudo make install

    - name: Install specific sudo version using apt-get
      run: apt-get install sudo=1.9.9-1ubuntu1.2
