name: sudo

on:
  push:
    branches: [ staging, sudo ]
  pull_request:
    branches: [ staging, sudo ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-24.04]
        include:
          - os: ubuntu-22.04
            cache-path: ${{ github.workspace }}/vcpkg_cache

    env:  
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      VCPKG_DEFAULT_BINARY_CACHE: ${{ matrix.cache-path }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update package list on Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get update
