name: sudo

on:
  push:
    branches: [ staging, sudo ]
  pull_request:
    branches: [ staging, sudo ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ ubuntu-24.04, ubuntu-22.04 ]
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache

    steps:
    - name: install sudo
      run: |
        sudo apt update
          #### sudo available in ubuntu
        
