name: sudo

on:
  push:
    branches: [staging, sudo]
  pull_request:
    branches: [staging, sudo]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache

    steps:
    - name: Update package list
      run: sudo apt update

    - name: Install necessary packages
      run: sudo apt install -y git 
