name: sudo

on:
  push:
    branches: [ staging, sudo ]
  pull_request:
    branches: [ staging, sudo ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            cache-path: ${{ github.workspace }}/vcpkg_cache
    env:  
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      VCPKG_DEFAULT_BINARY_CACHE: ${{ matrix.cache-path }}

    steps:
    - name: Update and install sudo
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install sudo
