name: sudo

on:
  push:
    branches: [ staging, sudo ]
  pull_request:
      branches: [ staging, sudo ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-24.04]
        include:
          - os: ubuntu-latest
            cache-path: ${{ github.workspace }}/vcpkg_cache
          - os: macos-latest
            cache-path: ${{ github.workspace }}/vcpkg_cache
    env:  
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      VCPKG_DEFAULT_BINARY_CACHE: ${{ matrix.cache-path }}

    steps:
    - name: install sudo
      if: matrix.os == 'ubuntu-latest'
      run: apt update && apt install sudo
