name: Test VCToolsRedistDir

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-2019
    steps:
      - name: Check if VCToolsRedistDir exists
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          
          :: Print all environment variables for debugging
          echo Listing environment variables:
          set

          :: Check VCToolsInstallDir and VCToolsRedistDir
          echo VCToolsInstallDir: %VCToolsInstallDir%
          echo VCToolsRedistDir: %VCToolsRedistDir%
          
          if not defined VCToolsRedistDir (
            echo Error: Environment variable VCToolsRedistDir is not set.
            exit /b 1
          )

