name: Check VCToolsRedistDir

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: windows-2019
    steps:
      - name: Check VCToolsRedistDir
        shell: cmd
        run: |
          :: Manually set the VCToolsRedistDir variable
          set VCToolsRedistDir="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Redist\MSVC\14.40.33816.0\x64\"

          :: Output the variable to confirm
          echo VCToolsRedistDir is set to: %VCToolsRedistDir%

          :: Check if the directory exists
          if exist %VCToolsRedistDir% (
            echo The VCToolsRedistDir path exists.
          ) else (
            echo The VCToolsRedistDir path does not exist: %VCToolsRedistDir%
            exit /b 1
          )
